import type { SystemInfoRes } from './contract'

// Generated by scripts/sync-version.mjs. Do not edit manually.
export const BOOKDOCK_BUILD_INFO = {
  version: '0.3.3',
  repositoryUrl: 'https://github.com/BookdockDevs/bookdock',
  releasesUrl: 'https://github.com/BookdockDevs/bookdock/releases',
} satisfies SystemInfoRes
