export const ErrorCode = {
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  SHELF_NOT_FOUND: 'SHELF_NOT_FOUND',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ANNOTATION_NOT_FOUND: 'ANNOTATION_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
  LAST_OWNER: 'LAST_OWNER',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  BOOK_NOT_FOUND: 404,
  SHELF_NOT_FOUND: 404,
  TAG_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  ANNOTATION_NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  USERNAME_TAKEN: 409,
  REGISTRATION_DISABLED: 403,
  ACCOUNT_DISABLED: 403,
  CANNOT_MODIFY_SELF: 400,
  LAST_OWNER: 400,
  VALIDATION_ERROR: 400,
  UPLOAD_TOO_LARGE: 413,
  UNSUPPORTED_FORMAT: 415,
  INTERNAL_ERROR: 500,
}
