export type { AiReadingScope, AiToolName, BookFormat, CoverPaletteId, SortField, ReadStatus } from './constants'
export { AI_CORE_SYSTEM_PROMPT, AI_DEFAULT_ASSISTANT_MODE_PROMPT, AI_DEFAULT_READING_SCOPE, AI_MAX_ASSISTANT_MODES, AI_MAX_CHAT_PROMPT_CHARS, AI_MAX_CHAPTER_REFERENCES, AI_MAX_CONTEXT_CHARS, AI_MAX_INDEX_CORPUS_CHARS, AI_READING_SCOPES, AI_TOOL_NAMES, AUTH_PASSWORD_MAX_LENGTH, AUTH_PASSWORD_MIN_LENGTH, AUTH_REGISTER_USERNAME_MAX_LENGTH, AUTH_USERNAME_MAX_LENGTH, BOOK_FORMATS, COVER_PALETTE_IDS, normalizeAiToolName, READ_STATUSES, PAGINATION, SORT_FIELDS } from './constants'
export { normalizeAiCitationMarkers, sanitizeAiCitationMarkers } from './ai-citations'
export { expandAiPrompt, getAiPromptVariables } from './ai-prompts'
export type { AiPromptValues, AiPromptVariable } from './ai-prompts'

export type { AccessTokenDuration, AccessTokenPermission, AccessTokenPermissionDefinition } from './access-tokens'
export {
  ACCESS_TOKEN_DURATIONS,
  ACCESS_TOKEN_NAME_MAX_LENGTH,
  ACCESS_TOKEN_PERMISSION_FREE_ENDPOINTS,
  ACCESS_TOKEN_PERMISSION_REGISTRY,
  ACCESS_TOKEN_PERMISSIONS,
  matchesEndpointPattern,
  requiredPermissionFor,
} from './access-tokens'

export type {
  User,
  Book,
  Shelf,
  Tag,
  BookTag,
  ReadingProgress,
  ReadingRecord,
  Settings,
  AnnotationType,
  AnnotationStyle,
  Annotation,
  ReplacementApplyTo,
  ReplacementMatchType,
  ReplacementScope,
  TextReplacement,
  ViewSettings,
  TocRulePattern,
  TocRule,
} from './domain'

export type {
  ApiResponse,
  ApiErrorBody,
  PaginatedResponse,
  BookListRes,
  LegadoBookSearchItem,
  LegadoSearchRes,
  LegadoExploreCategory,
  LegadoExploreConfigRes,
  LegadoBookInfoRes,
  LegadoChapterItem,
  LegadoTocRes,
  LegadoChapterContentRes,
  HealthCheckRes,
  LoginReq,
  LoginRes,
  SetupReq,
  SetupRes,
  SetupRequiredRes,
  MeRes,
  UpdateUsernameReq,
  AccountRes,
  InstanceInfoRes,
  UpdateInstanceReq,
  RegisterReq,
  RegisterRes,
  ChangePasswordReq,
  AdminUserRes,
  UpdateUserReq,
  SettingsRes,
  SettingsUpdateReq,
  TrashSettings,
  LibrarySettings,
  IntegrationsSettings,
  LegadoAccessKeyDuration,
  LegadoAccessKeyInfo,
  LegadoAccessKeyCreateRes,
  AccessToken,
  AccessTokenListRes,
  AccessTokenCreateReq,
  AccessTokenCreateRes,
  AccessTokenUpdateReq,
  TtsEngine,
  TtsProvider,
  FontPreference,
  FontPreferences,
  TtsProviderRes,
  TtsServiceRes,
  TtsServiceCreateReq,
  TtsServiceUpdateReq,
  TtsVoiceRes,
  TtsSpeechReq,
  TtsEdgeSpeechReq,
  AiContextReq,
  AiHistoryMessage,
  AiChatReq,
  AiRetryRecipe,
  AiGenerationState,
  AiGenerationTerminalReason,
  AiToolEvent,
  AiCitationEvent,
  AiNormalizedEvent,
  AiGenerationEvent,
  AiGenerationUsage,
  AiRetrievalSource,
  AiRetrievalCandidateSource,
  AiRetrievalFallbackReason,
  AiRetrievalTopResult,
  AiRetrievalDiagnostics,
  AiGenerationDiagnostics,
  AiGenerationRunRes,
  AiMessageEventRes,
  AiThreadSettings,
  AiConversationSettings,
  AiCitation,
  AiMessageRes,
  AiMessageRevisionRes,
  AiThreadRes,
  AiThreadDetailRes,
  AiThreadCreateReq,
  AiThreadUpdateReq,
  AiThreadListReq,
  AiIndexStatus,
  AiEmbeddingStatus,
  AiIndexChapter,
  AiIndexReq,
  AiIndexRes,
  AiSearchReq,
  AiSearchResultRes,
  AiSearchRes,
  AiStatusRes,
  AiConfigRes,
  AiConfigUpdateReq,
  AiContextReceipt,
  AiProvider,
  AiProviderRes,
  AiProtocol,
  AiModelCapabilities,
  AiModelRes,
  AiModelKind,
  AiPromptScope,
  AiPromptTemplate,
  AiPromptTemplateInput,
  AiAssistantMode,
  AiAssistantModeInput,
  AiChapterReference,
  AiModelDiscoveryReq,
  AiConfigTestReq,
  AiConnectionTestRes,
  AiProfileRes,
  AiProfileCreateReq,
  AiProfileUpdateReq,
  AiContextPlan,
  AiContextTruncationReason,
  FontScope,
  FontListItem,
  ShelfListItem,
  ShelfCreateReq,
  ShelfUpdateReq,
  ShelfReorderReq,
  TagListItem,
  TagCreateReq,
  TagUpdateReq,
  TagReorderReq,
  BookMembershipReq,
  BookListItem,
  BookMetadata,
  BookMeta,
  BookDetailRes,
  Chapter,
  ChapterListRes,
  UploadBookRes,
  ReadingProgressUpdateReq,
  ReadingProgressRes,
  RateSample,
  ReadingRecordCreateReq,
  ReadingRecordSummaryRes,
  ReadingRecordDailyItem,
  ReadingRecordHourlyItem,
  ReadingRecordBookItem,
  ReadingRecordBookDetailRes,
  ReadingSessionItem,
  ReadingSessionUpdateReq,
  ReadingDetailManualItem,
  ReadingDetailAutoDayItem,
  ReadingDetailItem,
  ReadingRecordTagItem,
  AnnotationCreateReq,
  AnnotationUpdateReq,
  AnnotationRes,
  ReplacementCreateReq,
  ReplacementUpdateReq,
  ReplacementOverrideReq,
  TextReplacementRes,
  TocRuleCreateReq,
  TocRuleUpdateReq,
  TocRuleReorderReq,
  TocRuleRes,
  TocRuleListRes,
  TocPreviewReq,
  TocPreviewChapter,
  TocPreviewRes,
  ReTocReq,
  AppendContentReq,
  AppendContentCandidate,
  AppendContentPreviewRes,
} from './contract'

export {
  bookFormatSchema,
  marginalFieldSchema,
  clickAreaModeSchema,
  loginSchema,
  paginationSchema,
  legadoSearchSchema,
  legadoExploreSchema,
  legadoAccessKeySchema,
  accessTokenCreateSchema,
  accessTokenUpdateSchema,
  readingProgressUpdateSchema,
  readingRecordCreateSchema,
  readingSessionUpdateSchema,
  readingSessionListSchema,
  readingDetailListSchema,
  readingRecordRangeSchema,
  readingRecordHourlySchema,
  settingsUpdateSchema,
  ttsServiceCreateSchema,
  ttsServiceUpdateSchema,
  ttsSpeechSchema,
  ttsEdgeSpeechSchema,
  aiProviderSchema,
  aiChatSchema,
  aiThreadCreateSchema,
  aiThreadUpdateSchema,
  aiThreadListSchema,
  aiGenerationRunIdSchema,
  aiMessageIdSchema,
  aiIndexStatusSchema,
  aiIndexSchema,
  aiSearchSchema,
  aiConfigUpdateSchema,
  aiModelDiscoverySchema,
  aiConfigTestSchema,
  aiProfileCreateSchema,
  aiProfileUpdateSchema,
  annotationCreateSchema,
  annotationUpdateSchema,
  replacementCreateSchema,
  replacementUpdateSchema,
  replacementOverrideSchema,
  tocRulePatternSchema,
  tocRulePatternsSchema,
  tocRuleCreateSchema,
  tocRuleUpdateSchema,
  tocRuleReorderSchema,
  tocPreviewSchema,
  reTocSchema,
  appendContentSchema,
  setupSchema,
  setupRequiredSchema,
  registerSchema,
  changePasswordSchema,
  updateUsernameSchema,
  updateInstanceSchema,
  updateUserSchema,
  shelfCreateSchema,
  shelfUpdateSchema,
  shelfReorderSchema,
  tagCreateSchema,
  tagUpdateSchema,
  tagReorderSchema,
  bookMembershipSchema,
  bookMetadataSchema,
  viewSettingsSchema,
  bookUpdateSchema,
} from './schema'

export { ErrorCode, ErrorHttpStatus } from './errors'

export { getAiModelCapabilityFlags, isAiEmbeddingModel } from './ai-models'

export {
  applyRuleToText,
  applyRuleToRuns,
  applyTitleReplacements,
  applyPointMatch,
  compileReplacementRegex,
  countRuleInText,
  findPointMatch,
  getReplacementEdits,
  type PointMatch,
  type ReplacementEdit,
  type ReplacementRuleLike,
  type TextRun,
} from './text-replacement-engine'
