export type { BookFormat, SortField, ReadStatus } from './constants'
export { AI_MAX_INDEX_CORPUS_CHARS, BOOK_FORMATS, READ_STATUSES, PAGINATION, SORT_FIELDS } from './constants'

export type {
  User,
  Book,
  Shelf,
  Tag,
  BookTag,
  ReadingProgress,
  ReadingRecord,
  Settings,
  AnnotationType,
  AnnotationStyle,
  Annotation,
  TransformMatchType,
  TransformScope,
  TextTransform,
  ViewSettings,
  TocRulePattern,
  TocRule,
} from './domain'

export type {
  ApiResponse,
  ApiErrorBody,
  PaginatedResponse,
  HealthCheckRes,
  LoginReq,
  LoginRes,
  SetupReq,
  SetupRes,
  SetupRequiredRes,
  MeRes,
  UpdateUsernameReq,
  AccountRes,
  InstanceInfoRes,
  UpdateInstanceReq,
  RegisterReq,
  RegisterRes,
  ChangePasswordReq,
  AdminUserRes,
  UpdateUserReq,
  SettingsRes,
  SettingsUpdateReq,
  TrashSettings,
  TtsEngine,
  TtsProvider,
  TtsProviderRes,
  TtsServiceRes,
  TtsServiceCreateReq,
  TtsServiceUpdateReq,
  TtsVoiceRes,
  TtsSpeechReq,
  AiContextReq,
  AiHistoryMessage,
  AiChatReq,
  AiCitation,
  AiMessageRes,
  AiThreadRes,
  AiThreadDetailRes,
  AiThreadCreateReq,
  AiThreadUpdateReq,
  AiThreadListReq,
  AiIndexStatus,
  AiEmbeddingStatus,
  AiIndexChapter,
  AiIndexReq,
  AiIndexRes,
  AiSearchReq,
  AiSearchResultRes,
  AiSearchRes,
  AiStatusRes,
  AiConfigRes,
  AiConfigUpdateReq,
  AiContextReceipt,
  AiProvider,
  AiProviderRes,
  AiProtocol,
  AiModelCapabilities,
  AiModelRes,
  AiModelKind,
  AiPromptScope,
  AiPromptTemplate,
  AiPromptTemplateInput,
  AiModelDiscoveryReq,
  AiConfigTestReq,
  AiConnectionTestRes,
  AiProfileRes,
  AiProfileCreateReq,
  AiProfileUpdateReq,
  FontScope,
  FontListItem,
  ShelfListItem,
  ShelfCreateReq,
  ShelfUpdateReq,
  ShelfReorderReq,
  TagListItem,
  TagCreateReq,
  TagUpdateReq,
  BookMembershipReq,
  BookListItem,
  BookMetadata,
  BookMeta,
  BookDetailRes,
  Chapter,
  ChapterListRes,
  UploadBookRes,
  ReadingProgressUpdateReq,
  ReadingProgressRes,
  RateSample,
  ReadingRecordCreateReq,
  ReadingRecordSummaryRes,
  ReadingRecordDailyItem,
  ReadingRecordHourlyItem,
  ReadingRecordBookItem,
  ReadingRecordBookDetailRes,
  ReadingSessionItem,
  ReadingSessionUpdateReq,
  ReadingDetailManualItem,
  ReadingDetailAutoDayItem,
  ReadingDetailItem,
  ReadingRecordTagItem,
  AnnotationCreateReq,
  AnnotationUpdateReq,
  AnnotationRes,
  TransformCreateReq,
  TransformUpdateReq,
  TransformOverrideReq,
  TextTransformRes,
  TocRuleCreateReq,
  TocRuleUpdateReq,
  TocRuleReorderReq,
  TocRuleRes,
  TocRuleListRes,
} from './contract'

export {
  bookFormatSchema,
  marginalFieldSchema,
  clickAreaModeSchema,
  loginSchema,
  paginationSchema,
  readingProgressUpdateSchema,
  readingRecordCreateSchema,
  readingSessionUpdateSchema,
  readingSessionListSchema,
  readingDetailListSchema,
  readingRecordRangeSchema,
  readingRecordHourlySchema,
  settingsUpdateSchema,
  ttsServiceCreateSchema,
  ttsServiceUpdateSchema,
  ttsSpeechSchema,
  aiProviderSchema,
  aiChatSchema,
  aiThreadCreateSchema,
  aiThreadUpdateSchema,
  aiThreadListSchema,
  aiIndexStatusSchema,
  aiIndexSchema,
  aiSearchSchema,
  aiConfigUpdateSchema,
  aiModelDiscoverySchema,
  aiConfigTestSchema,
  aiProfileCreateSchema,
  aiProfileUpdateSchema,
  annotationCreateSchema,
  annotationUpdateSchema,
  transformCreateSchema,
  transformUpdateSchema,
  transformOverrideSchema,
  tocRulePatternSchema,
  tocRuleCreateSchema,
  tocRuleUpdateSchema,
  tocRuleReorderSchema,
  setupSchema,
  setupRequiredSchema,
  registerSchema,
  changePasswordSchema,
  updateUsernameSchema,
  updateInstanceSchema,
  updateUserSchema,
  shelfCreateSchema,
  shelfUpdateSchema,
  shelfReorderSchema,
  tagCreateSchema,
  tagUpdateSchema,
  bookMembershipSchema,
  bookMetadataSchema,
  viewSettingsSchema,
  bookUpdateSchema,
} from './schema'

export { ErrorCode, ErrorHttpStatus } from './errors'

export { getAiModelCapabilityFlags, isAiEmbeddingModel } from './ai-models'

export {
  applyRuleToText,
  countRuleInText,
  findPointMatch,
  type TransformRuleLike,
  type TextRun,
} from './text-transform-engine'
