import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const checkOnly = process.argv.includes('--check')
const rootPackagePath = join(rootDir, 'package.json')
const buildInfoPath = join(rootDir, 'packages/shared/src/build-info.ts')
const packagePaths = [
  'apps/server/package.json',
  'apps/web/package.json',
  'packages/shared/package.json',
].map((file) => join(rootDir, file))

const rootPackage = JSON.parse(readFileSync(rootPackagePath, 'utf8'))
const version = rootPackage.version
if (typeof version !== 'string' || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(`Invalid root package version: ${String(version)}`)
}

const expectedBuildInfo = `import type { SystemInfoRes } from './contract'

// Generated by scripts/sync-version.mjs. Do not edit manually.
export const BOOKDOCK_BUILD_INFO = {
  version: '${version}',
  repositoryUrl: 'https://github.com/BookdockDevs/bookdock',
  releasesUrl: 'https://github.com/BookdockDevs/bookdock/releases',
} satisfies SystemInfoRes
`

const staleFiles = []
for (const packagePath of packagePaths) {
  const packageJson = JSON.parse(readFileSync(packagePath, 'utf8'))
  if (packageJson.version !== version) staleFiles.push(packagePath)
}
if (readFileSync(buildInfoPath, 'utf8') !== expectedBuildInfo) staleFiles.push(buildInfoPath)

if (checkOnly) {
  if (staleFiles.length > 0) {
    throw new Error(`Version-derived files are out of sync:\n${staleFiles.join('\n')}`)
  }
  console.log(`Version files are synchronized at ${version}.`)
} else {
  for (const packagePath of packagePaths) {
    const packageJson = JSON.parse(readFileSync(packagePath, 'utf8'))
    if (packageJson.version === version) continue
    packageJson.version = version
    writeFileSync(packagePath, `${JSON.stringify(packageJson, null, 2)}\n`)
  }
  if (readFileSync(buildInfoPath, 'utf8') !== expectedBuildInfo) writeFileSync(buildInfoPath, expectedBuildInfo)
  console.log(`Synchronized version files at ${version}.`)
}
